name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.3
  workflow_dispatch:  # Allows manual trigger
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.3)'
        required: true
        default: 'v1.0.3'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Extract version from tag
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "VERSION_NAME=${VERSION#v}" >> $GITHUB_OUTPUT
        
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Rename APK
      run: |
        mv app/build/outputs/apk/release/app-release-unsigned.apk \
           app/build/outputs/apk/release/DemantiaClockX-${{ steps.version.outputs.VERSION }}-release.apk
           
    - name: Read Release Notes
      id: release_notes
      run: |
        if [ -f "RELEASE_NOTES_${{ steps.version.outputs.VERSION }}.md" ]; then
          RELEASE_NOTES=$(cat "RELEASE_NOTES_${{ steps.version.outputs.VERSION }}.md")
        else
          RELEASE_NOTES="Release ${{ steps.version.outputs.VERSION }}"
        fi
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
        echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: DemantiaClockX ${{ steps.version.outputs.VERSION }}
        body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
        draft: false
        prerelease: false
        files: |
          app/build/outputs/apk/release/DemantiaClockX-${{ steps.version.outputs.VERSION }}-release.apk
          RELEASE_NOTES_${{ steps.version.outputs.VERSION }}.md
        
    - name: Notify Success
      run: |
        echo "✅ Release ${{ steps.version.outputs.VERSION }} created successfully!"
        echo "📦 APK: DemantiaClockX-${{ steps.version.outputs.VERSION }}-release.apk"
        echo "🔗 Check the release at: https://github.com/${{ github.repository }}/releases/tag/${{ steps.version.outputs.VERSION }}"